apiVersion: apps/v1
kind: Deployment
metadata:
  name: shelly-collector
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: shelly-collector
  template:
    metadata:
      labels:
        app: shelly-collector
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 10
      containers:
        - name: collector
          image: localhost/shelly-collector:1.0
          imagePullPolicy: Never
          env:
            - name: MQTT_HOST
              value: mosquitto
            - name: MQTT_PORT
              value: "1883"
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
