apiVersion: batch/v1
kind: CronJob
metadata:
  name: switchbot-collector-livingroom
  namespace: monitoring
spec:
  failedJobsHistoryLimit: 10  # default is 1
  schedule: "*/1 * * * *"  # every minute
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: collector
            image: localhost/switchbot-collector:0.9        # local image in containerd
            imagePullPolicy: Never                 # do not attempt to pull from registry
            env:
            - name: SWITCHBOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: switchbot-secret
                  key: SWITCHBOT_TOKEN
            - name: DEVICE_ID
              value: "C6E81B436DAA"
            - name: LOCATION
              value: "LivingRoom"
            - name: PUSHGATEWAY_URL
              value: "http://pushgateway.monitoring.svc:9091"

