apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: splunk
  name: splunk-svc
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 30080
  selector:
    run: splunk
  type: NodePort
status:
  loadBalancer: {}
